spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/swedtrac_workorder
    username: swedtrac
    password: swedtrac
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: swedtrac-workorder

server:
  port: 8080